[
{ "tag": "const", "name": "_G_BUFSIZ", "location": "macros.h:2008:18", "type": { "tag": "__int128_t" }, "value": 8192 },
{ "tag": "const", "name": "_G_NAMES_HAVE_UNDERSCORE", "location": "macros.h:2009:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "_IO_BOOLALPHA", "location": "macros.h:2010:18", "type": { "tag": "__int128_t" }, "value": 65536 },
{ "tag": "const", "name": "_G_USING_THUNKS", "location": "macros.h:2011:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_G_VTABLE_LABEL_HAS_LENGTH", "location": "macros.h:2012:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_G_VTABLE_LABEL_PREFIX", "location": "macros.h:2013:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "__vt_" },
{ "tag": "const", "name": "RAND_MAX", "location": "macros.h:2014:18", "type": { "tag": "__int128_t" }, "value": 2147483647 },
{ "tag": "const", "name": "EXIT_SUCCESS", "location": "macros.h:2015:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "EXIT_FAILURE", "location": "macros.h:2016:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_IO_SCIENTIFIC", "location": "macros.h:2017:18", "type": { "tag": "__int128_t" }, "value": 2048 },
{ "tag": "const", "name": "_IO_UNITBUF", "location": "macros.h:2018:18", "type": { "tag": "__int128_t" }, "value": 8192 },
{ "tag": "const", "name": "_IO_FIXED", "location": "macros.h:2019:18", "type": { "tag": "__int128_t" }, "value": 4096 },
{ "tag": "const", "name": "_IO_DONT_CLOSE", "location": "macros.h:2020:18", "type": { "tag": "__int128_t" }, "value": 32768 },
{ "tag": "const", "name": "_G_HAVE_MMAP", "location": "macros.h:2021:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_IO_STDIO", "location": "macros.h:2022:18", "type": { "tag": "__int128_t" }, "value": 16384 },
{ "tag": "const", "name": "_G_HAVE_MREMAP", "location": "macros.h:2023:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_G_HAVE_LONG_DOUBLE_IO", "location": "macros.h:2024:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_BITS_TYPESIZES_H", "location": "macros.h:2025:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_G_HAVE_IO_FILE_OPEN", "location": "macros.h:2026:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_G_HAVE_IO_GETLINE_INFO", "location": "macros.h:2027:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_G_IO_IO_FILE_VERSION", "location": "macros.h:2028:18", "type": { "tag": "__int128_t" }, "value": 131073 },
{ "tag": "const", "name": "_G_HAVE_BOOL", "location": "macros.h:2029:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_G_HAVE_ATEXIT", "location": "macros.h:2030:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_G_HAVE_SYS_CDEFS", "location": "macros.h:2031:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_G_HAVE_SYS_WAIT", "location": "macros.h:2032:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_G_NEED_STDARG_H", "location": "macros.h:2033:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_G_HAVE_PRINTF_FP", "location": "macros.h:2034:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_INIT_GAMECONTROLLER", "location": "macros.h:2035:18", "type": { "tag": "__int128_t" }, "value": 8192 },
{ "tag": "const", "name": "SDL_INIT_NOPARACHUTE", "location": "macros.h:2036:18", "type": { "tag": "__int128_t" }, "value": 1048576 },
{ "tag": "const", "name": "SDL_MIX_MAXVOLUME", "location": "macros.h:2037:18", "type": { "tag": "__int128_t" }, "value": 128 },
{ "tag": "const", "name": "SDL_DONTFREE", "location": "macros.h:2038:18", "type": { "tag": "__int128_t" }, "value": 4 },
{ "tag": "const", "name": "SDL_PREALLOC", "location": "macros.h:2039:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_RLEACCEL", "location": "macros.h:2040:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "SDL_SWSURFACE", "location": "macros.h:2041:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "__FD_SETSIZE", "location": "macros.h:2042:18", "type": { "tag": "__int128_t" }, "value": 1024 },
{ "tag": "const", "name": "RW_SEEK_END", "location": "macros.h:2043:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "RW_SEEK_SET", "location": "macros.h:2044:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "RW_SEEK_CUR", "location": "macros.h:2045:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_AUDIO_MASK_ENDIAN", "location": "macros.h:2046:18", "type": { "tag": "__int128_t" }, "value": 4096 },
{ "tag": "const", "name": "SDL_AUDIO_MASK_SIGNED", "location": "macros.h:2047:18", "type": { "tag": "__int128_t" }, "value": 32768 },
{ "tag": "const", "name": "SDL_AUDIO_MASK_BITSIZE", "location": "macros.h:2048:18", "type": { "tag": "__int128_t" }, "value": 255 },
{ "tag": "const", "name": "SDL_AUDIO_MASK_DATATYPE", "location": "macros.h:2049:18", "type": { "tag": "__int128_t" }, "value": 256 },
{ "tag": "const", "name": "_STRING_H", "location": "macros.h:2050:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "AUDIO_U16MSB", "location": "macros.h:2051:18", "type": { "tag": "__int128_t" }, "value": 4112 },
{ "tag": "const", "name": "SDL_WINDOWPOS_UNDEFINED", "location": "macros.h:2052:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "AUDIO_S16LSB", "location": "macros.h:2053:18", "type": { "tag": "__int128_t" }, "value": 32784 },
{ "tag": "const", "name": "AUDIO_U16LSB", "location": "macros.h:2054:18", "type": { "tag": "__int128_t" }, "value": 16 },
{ "tag": "const", "name": "SDL_WINDOWPOS_CENTERED_MASK", "location": "macros.h:2055:18", "type": { "tag": "__int128_t" }, "value": 805240832 },
{ "tag": "const", "name": "SDL_WINDOWPOS_CENTERED", "location": "macros.h:2056:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "AUDIO_S8", "location": "macros.h:2057:18", "type": { "tag": "__int128_t" }, "value": 32776 },
{ "tag": "const", "name": "AUDIO_S16MSB", "location": "macros.h:2058:18", "type": { "tag": "__int128_t" }, "value": 36880 },
{ "tag": "const", "name": "AUDIO_U8", "location": "macros.h:2059:18", "type": { "tag": "__int128_t" }, "value": 8 },
{ "tag": "const", "name": "SDL_WINDOWPOS_UNDEFINED_MASK", "location": "macros.h:2060:18", "type": { "tag": "__int128_t" }, "value": 536805376 },
{ "tag": "const", "name": "SDL_BIG_ENDIAN", "location": "macros.h:2061:18", "type": { "tag": "__int128_t" }, "value": 4321 },
{ "tag": "const", "name": "SDL_LIL_ENDIAN", "location": "macros.h:2062:18", "type": { "tag": "__int128_t" }, "value": 1234 },
{ "tag": "const", "name": "SDL_MUTEX_TIMEDOUT", "location": "macros.h:2063:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_MUTEX_MAXWAIT", "location": "macros.h:2064:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "_SVID_SOURCE", "location": "macros.h:2065:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIX16", "location": "macros.h:2066:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "X" },
{ "tag": "const", "name": "__USE_FORTIFY_LEVEL", "location": "macros.h:2067:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "PRIX32", "location": "macros.h:2068:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "X" },
{ "tag": "const", "name": "PRIX8", "location": "macros.h:2069:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "X" },
{ "tag": "const", "name": "PRIxFAST64", "location": "macros.h:2070:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lx" },
{ "tag": "const", "name": "PRIxFAST8", "location": "macros.h:2071:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "x" },
{ "tag": "const", "name": "PRIxFAST32", "location": "macros.h:2072:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lx" },
{ "tag": "const", "name": "__USE_SVID", "location": "macros.h:2073:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIxLEAST64", "location": "macros.h:2074:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lx" },
{ "tag": "const", "name": "__USE_MISC", "location": "macros.h:2075:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIxLEAST32", "location": "macros.h:2076:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "x" },
{ "tag": "const", "name": "PRIxLEAST16", "location": "macros.h:2077:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "x" },
{ "tag": "const", "name": "__USE_ATFILE", "location": "macros.h:2078:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_POSIX_C_SOURCE", "location": "macros.h:2079:18", "type": { "tag": "__int128_t" }, "value": 200809 },
{ "tag": "const", "name": "PRIXFAST64", "location": "macros.h:2080:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lX" },
{ "tag": "const", "name": "_POSIX_SOURCE", "location": "macros.h:2081:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_BSD_SOURCE", "location": "macros.h:2082:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIXFAST8", "location": "macros.h:2083:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "X" },
{ "tag": "const", "name": "PRIXFAST16", "location": "macros.h:2084:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lX" },
{ "tag": "const", "name": "PRIXLEAST64", "location": "macros.h:2085:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lX" },
{ "tag": "const", "name": "PRIxFAST16", "location": "macros.h:2086:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lx" },
{ "tag": "const", "name": "PRIXLEAST32", "location": "macros.h:2087:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "X" },
{ "tag": "const", "name": "__USE_ANSI", "location": "macros.h:2088:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIXLEAST16", "location": "macros.h:2089:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "X" },
{ "tag": "const", "name": "PRIXLEAST8", "location": "macros.h:2090:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "X" },
{ "tag": "const", "name": "PRIX64", "location": "macros.h:2091:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lX" },
{ "tag": "const", "name": "__USE_POSIX199506", "location": "macros.h:2092:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIuPTR", "location": "macros.h:2093:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lu" },
{ "tag": "const", "name": "PRIxPTR", "location": "macros.h:2094:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lx" },
{ "tag": "const", "name": "__USE_POSIX199309", "location": "macros.h:2095:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIoPTR", "location": "macros.h:2096:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lo" },
{ "tag": "const", "name": "PRIiPTR", "location": "macros.h:2097:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "li" },
{ "tag": "const", "name": "PRIdPTR", "location": "macros.h:2098:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "ld" },
{ "tag": "const", "name": "PRIXMAX", "location": "macros.h:2099:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lX" },
{ "tag": "const", "name": "__USE_ISOC95", "location": "macros.h:2100:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIuMAX", "location": "macros.h:2101:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lu" },
{ "tag": "const", "name": "__USE_ISOC99", "location": "macros.h:2102:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__USE_POSIX2", "location": "macros.h:2103:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIiMAX", "location": "macros.h:2104:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "li" },
{ "tag": "const", "name": "PRIoMAX", "location": "macros.h:2105:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lo" },
{ "tag": "const", "name": "PRIXFAST32", "location": "macros.h:2106:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lX" },
{ "tag": "const", "name": "__USE_POSIX", "location": "macros.h:2107:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIdMAX", "location": "macros.h:2108:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "ld" },
{ "tag": "const", "name": "SCNdLEAST32", "location": "macros.h:2109:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "d" },
{ "tag": "const", "name": "PRIxMAX", "location": "macros.h:2110:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lx" },
{ "tag": "const", "name": "SCNdLEAST64", "location": "macros.h:2111:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "ld" },
{ "tag": "const", "name": "__USE_BSD", "location": "macros.h:2112:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SCNdLEAST8", "location": "macros.h:2113:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hhd" },
{ "tag": "const", "name": "SCNdLEAST16", "location": "macros.h:2114:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hd" },
{ "tag": "const", "name": "SDL_HINT_RENDER_DRIVER", "location": "macros.h:2115:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "SDL_RENDER_DRIVER" },
{ "tag": "const", "name": "__USE_XOPEN2K", "location": "macros.h:2116:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_HINT_FRAMEBUFFER_ACCELERATION", "location": "macros.h:2117:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "SDL_FRAMEBUFFER_ACCELERATION" },
{ "tag": "const", "name": "SCNd8", "location": "macros.h:2118:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hhd" },
{ "tag": "const", "name": "PRIXPTR", "location": "macros.h:2119:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lX" },
{ "tag": "const", "name": "__USE_XOPEN2K8", "location": "macros.h:2120:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_HINT_RENDER_SCALE_QUALITY", "location": "macros.h:2121:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "SDL_RENDER_SCALE_QUALITY" },
{ "tag": "const", "name": "SCNd64", "location": "macros.h:2122:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "ld" },
{ "tag": "const", "name": "SDL_VIDEO_DRIVER_X11_XSHAPE", "location": "macros.h:2123:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_RWOPS_WINFILE", "location": "macros.h:2124:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_VIDEO_DRIVER_X11_XVIDMODE", "location": "macros.h:2125:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_RWOPS_STDFILE", "location": "macros.h:2126:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "SDL_VIDEO_DRIVER_X11_SUPPORTS_GENERIC_EVENTS", "location": "macros.h:2127:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_BITS_BYTESWAP_H", "location": "macros.h:2128:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SCNd16", "location": "macros.h:2129:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hd" },
{ "tag": "const", "name": "SDL_VIDEO_DRIVER_X11_CONST_PARAM_XEXTADDDISPLAY", "location": "macros.h:2130:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_RWOPS_UNKNOWN", "location": "macros.h:2131:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "SDL_VIDEO_DRIVER_X11_XINERAMA", "location": "macros.h:2132:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_RWOPS_JNIFILE", "location": "macros.h:2133:18", "type": { "tag": "__int128_t" }, "value": 3 },
{ "tag": "const", "name": "SDL_VIDEO_DRIVER_X11_XINPUT2", "location": "macros.h:2134:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_MM_FLUSH_ZERO_OFF", "location": "macros.h:2135:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "SDL_VIDEO_DRIVER_X11_XRANDR", "location": "macros.h:2136:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_RWOPS_MEMORY_RO", "location": "macros.h:2137:18", "type": { "tag": "__int128_t" }, "value": 5 },
{ "tag": "const", "name": "_MM_FLUSH_ZERO_ON", "location": "macros.h:2138:18", "type": { "tag": "__int128_t" }, "value": 32768 },
{ "tag": "const", "name": "SDL_RWOPS_MEMORY", "location": "macros.h:2139:18", "type": { "tag": "__int128_t" }, "value": 4 },
{ "tag": "const", "name": "SCNd32", "location": "macros.h:2140:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "d" },
{ "tag": "const", "name": "SDL_VIDEO_OPENGL_GLX", "location": "macros.h:2141:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_POWER_LINUX", "location": "macros.h:2142:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_ASSEMBLY_ROUTINES", "location": "macros.h:2143:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_FEATURES_H", "location": "macros.h:2144:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_SYS_TYPES_H", "location": "macros.h:2145:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_HINT_VIDEO_X11_XINERAMA", "location": "macros.h:2146:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "SDL_VIDEO_X11_XINERAMA" },
{ "tag": "const", "name": "SDL_HINT_XINPUT_ENABLED", "location": "macros.h:2147:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "SDL_XINPUT_ENABLED" },
{ "tag": "const", "name": "SDL_VIDEO_DRIVER_X11_HAS_XKBKEYCODETOKEYSYM", "location": "macros.h:2148:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_MM_ROUND_MASK", "location": "macros.h:2149:18", "type": { "tag": "__int128_t" }, "value": 24576 },
{ "tag": "const", "name": "SDL_VIDEO_RENDER_OGL", "location": "macros.h:2150:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_HINT_ALLOW_TOPMOST", "location": "macros.h:2151:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "SDL_ALLOW_TOPMOST" },
{ "tag": "const", "name": "SDL_VIDEO_OPENGL", "location": "macros.h:2152:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_HINT_VIDEO_X11_XRANDR", "location": "macros.h:2153:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "SDL_VIDEO_X11_XRANDR" },
{ "tag": "const", "name": "_MM_FLUSH_ZERO_MASK", "location": "macros.h:2154:18", "type": { "tag": "__int128_t" }, "value": 32768 },
{ "tag": "const", "name": "SDL_VIDEO_DRIVER_DUMMY", "location": "macros.h:2155:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_MM_EXCEPT_DIV_ZERO", "location": "macros.h:2156:18", "type": { "tag": "__int128_t" }, "value": 4 },
{ "tag": "const", "name": "_MM_ROUND_DOWN", "location": "macros.h:2157:18", "type": { "tag": "__int128_t" }, "value": 8192 },
{ "tag": "const", "name": "SDL_VIDEO_DRIVER_X11", "location": "macros.h:2158:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_MM_EXCEPT_DENORM", "location": "macros.h:2159:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "_MM_ROUND_TOWARD_ZERO", "location": "macros.h:2160:18", "type": { "tag": "__int128_t" }, "value": 24576 },
{ "tag": "const", "name": "SDL_VIDEO_DRIVER_X11_DYNAMIC", "location": "macros.h:2161:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "libX11.so.6" },
{ "tag": "const", "name": "_MM_EXCEPT_INVALID", "location": "macros.h:2162:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_MM_ROUND_UP", "location": "macros.h:2163:18", "type": { "tag": "__int128_t" }, "value": 16384 },
{ "tag": "const", "name": "SDL_HINT_RENDER_OPENGL_SHADERS", "location": "macros.h:2164:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "SDL_RENDER_OPENGL_SHADERS" },
{ "tag": "const", "name": "SDL_BUTTON_X2", "location": "macros.h:2165:18", "type": { "tag": "__int128_t" }, "value": 5 },
{ "tag": "const", "name": "__BIT_TYPES_DEFINED__", "location": "macros.h:2166:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_MM_EXCEPT_MASK", "location": "macros.h:2167:18", "type": { "tag": "__int128_t" }, "value": 63 },
{ "tag": "const", "name": "SDL_THREAD_PTHREAD", "location": "macros.h:2168:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_MM_EXCEPT_INEXACT", "location": "macros.h:2169:18", "type": { "tag": "__int128_t" }, "value": 32 },
{ "tag": "const", "name": "SDL_BUTTON_LEFT", "location": "macros.h:2170:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__LITTLE_ENDIAN", "location": "macros.h:2171:18", "type": { "tag": "__int128_t" }, "value": 1234 },
{ "tag": "const", "name": "SDL_BUTTON_X1", "location": "macros.h:2172:18", "type": { "tag": "__int128_t" }, "value": 4 },
{ "tag": "const", "name": "SDL_THREAD_PTHREAD_RECURSIVE_MUTEX", "location": "macros.h:2173:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_MM_EXCEPT_UNDERFLOW", "location": "macros.h:2174:18", "type": { "tag": "__int128_t" }, "value": 16 },
{ "tag": "const", "name": "SDL_BUTTON_MIDDLE", "location": "macros.h:2175:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "_ENDIAN_H", "location": "macros.h:2176:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_TIMER_UNIX", "location": "macros.h:2177:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_MM_EXCEPT_OVERFLOW", "location": "macros.h:2178:18", "type": { "tag": "__int128_t" }, "value": 8 },
{ "tag": "const", "name": "__PDP_ENDIAN", "location": "macros.h:2179:18", "type": { "tag": "__int128_t" }, "value": 3412 },
{ "tag": "const", "name": "PRIx64", "location": "macros.h:2180:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lx" },
{ "tag": "const", "name": "__BIG_ENDIAN", "location": "macros.h:2181:18", "type": { "tag": "__int128_t" }, "value": 4321 },
{ "tag": "const", "name": "SDL_VIDEO_DRIVER_X11_DYNAMIC_XRANDR", "location": "macros.h:2182:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "libXrandr.so.2" },
{ "tag": "const", "name": "PRIxLEAST8", "location": "macros.h:2183:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "x" },
{ "tag": "const", "name": "SDL_VIDEO_DRIVER_X11_DYNAMIC_XVIDMODE", "location": "macros.h:2184:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "libXxf86vm.so.1" },
{ "tag": "const", "name": "SDL_VIDEO_DRIVER_X11_XCURSOR", "location": "macros.h:2185:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIx16", "location": "macros.h:2186:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "x" },
{ "tag": "const", "name": "SDL_VIDEO_DRIVER_X11_DYNAMIC_XEXT", "location": "macros.h:2187:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "libXext.so.6" },
{ "tag": "const", "name": "PRIx32", "location": "macros.h:2188:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "x" },
{ "tag": "const", "name": "SDL_VIDEO_DRIVER_X11_DYNAMIC_XCURSOR", "location": "macros.h:2189:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "libXcursor.so.1" },
{ "tag": "const", "name": "PRIuFAST64", "location": "macros.h:2190:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lu" },
{ "tag": "const", "name": "_MM_MASK_MASK", "location": "macros.h:2191:18", "type": { "tag": "__int128_t" }, "value": 8064 },
{ "tag": "const", "name": "_MM_MASK_OVERFLOW", "location": "macros.h:2192:18", "type": { "tag": "__int128_t" }, "value": 1024 },
{ "tag": "const", "name": "PRIx8", "location": "macros.h:2193:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "x" },
{ "tag": "const", "name": "PRIuFAST32", "location": "macros.h:2194:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lu" },
{ "tag": "const", "name": "SDL_VIDEO_DRIVER_X11_DYNAMIC_XINERAMA", "location": "macros.h:2195:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "libXinerama.so.1" },
{ "tag": "const", "name": "PRIuFAST16", "location": "macros.h:2196:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lu" },
{ "tag": "const", "name": "SDL_VIDEO_DRIVER_X11_DYNAMIC_XINPUT2", "location": "macros.h:2197:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "libXi.so.6" },
{ "tag": "const", "name": "PRIuFAST8", "location": "macros.h:2198:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "u" },
{ "tag": "const", "name": "_MM_MASK_INEXACT", "location": "macros.h:2199:18", "type": { "tag": "__int128_t" }, "value": 4096 },
{ "tag": "const", "name": "_MM_ROUND_NEAREST", "location": "macros.h:2200:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "SDL_BUTTON_RIGHT", "location": "macros.h:2201:18", "type": { "tag": "__int128_t" }, "value": 3 },
{ "tag": "const", "name": "_MM_MASK_INVALID", "location": "macros.h:2202:18", "type": { "tag": "__int128_t" }, "value": 128 },
{ "tag": "const", "name": "SDL_HINT_ORIENTATIONS", "location": "macros.h:2203:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "SDL_IOS_ORIENTATIONS" },
{ "tag": "const", "name": "SIZEOF_VOIDP", "location": "macros.h:2204:18", "type": { "tag": "__int128_t" }, "value": 8 },
{ "tag": "const", "name": "SDL_HINT_VIDEO_X11_XVIDMODE", "location": "macros.h:2205:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "SDL_VIDEO_X11_XVIDMODE" },
{ "tag": "const", "name": "SDL_HINT_GAMECONTROLLERCONFIG", "location": "macros.h:2206:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "SDL_GAMECONTROLLERCONFIG" },
{ "tag": "const", "name": "_MM_MASK_DIV_ZERO", "location": "macros.h:2207:18", "type": { "tag": "__int128_t" }, "value": 512 },
{ "tag": "const", "name": "_MM_MASK_DENORM", "location": "macros.h:2208:18", "type": { "tag": "__int128_t" }, "value": 256 },
{ "tag": "const", "name": "_INTTYPES_H", "location": "macros.h:2209:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_STRINGS_H", "location": "macros.h:2210:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_MAX_LOG_MESSAGE", "location": "macros.h:2211:18", "type": { "tag": "__int128_t" }, "value": 4096 },
{ "tag": "const", "name": "SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS", "location": "macros.h:2212:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS" },
{ "tag": "const", "name": "SDL_HINT_GRAB_KEYBOARD", "location": "macros.h:2213:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "SDL_GRAB_KEYBOARD" },
{ "tag": "const", "name": "SDL_HINT_RENDER_VSYNC", "location": "macros.h:2214:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "SDL_RENDER_VSYNC" },
{ "tag": "const", "name": "__WCHAR_MAX", "location": "macros.h:2215:18", "type": { "tag": "__int128_t" }, "value": 2147483647 },
{ "tag": "const", "name": "_STDINT_H", "location": "macros.h:2216:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__WCHAR_MIN", "location": "macros.h:2217:18", "type": { "tag": "__int128_t" }, "value": -2147483648 },
{ "tag": "const", "name": "SDL_HINT_IDLE_TIMER_DISABLED", "location": "macros.h:2218:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "SDL_IOS_IDLE_TIMER_DISABLED" },
{ "tag": "const", "name": "_BITS_WCHAR_H", "location": "macros.h:2219:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__LINUX__", "location": "macros.h:2220:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_ICONV_EILSEQ", "location": "macros.h:2221:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "SDL_ICONV_E2BIG", "location": "macros.h:2222:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "_MM_MASK_UNDERFLOW", "location": "macros.h:2223:18", "type": { "tag": "__int128_t" }, "value": 2048 },
{ "tag": "const", "name": "SDL_ICONV_ERROR", "location": "macros.h:2224:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "SCNiLEAST32", "location": "macros.h:2225:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "i" },
{ "tag": "const", "name": "SCNiLEAST64", "location": "macros.h:2226:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "li" },
{ "tag": "const", "name": "SCNiFAST16", "location": "macros.h:2227:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "li" },
{ "tag": "const", "name": "SCNiFAST32", "location": "macros.h:2228:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "li" },
{ "tag": "const", "name": "SCNiFAST8", "location": "macros.h:2229:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hhi" },
{ "tag": "const", "name": "_ICONV_H", "location": "macros.h:2230:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SCNiFAST64", "location": "macros.h:2231:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "li" },
{ "tag": "const", "name": "SCNu8", "location": "macros.h:2232:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hhu" },
{ "tag": "const", "name": "SCNu16", "location": "macros.h:2233:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hu" },
{ "tag": "const", "name": "SCNu32", "location": "macros.h:2234:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "u" },
{ "tag": "const", "name": "SCNu64", "location": "macros.h:2235:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lu" },
{ "tag": "const", "name": "SCNdFAST8", "location": "macros.h:2236:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hhd" },
{ "tag": "const", "name": "SCNdFAST16", "location": "macros.h:2237:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "ld" },
{ "tag": "const", "name": "HAVE_DBUS_DBUS_H", "location": "macros.h:2238:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SCNdFAST32", "location": "macros.h:2239:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "ld" },
{ "tag": "const", "name": "HAVE_LIBUDEV_H", "location": "macros.h:2240:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SCNdFAST64", "location": "macros.h:2241:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "ld" },
{ "tag": "const", "name": "HAVE_SIGNAL_H", "location": "macros.h:2242:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SCNi16", "location": "macros.h:2243:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hi" },
{ "tag": "const", "name": "SCNi32", "location": "macros.h:2244:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "i" },
{ "tag": "const", "name": "SCNi64", "location": "macros.h:2245:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "li" },
{ "tag": "const", "name": "SCNiLEAST8", "location": "macros.h:2246:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hhi" },
{ "tag": "const", "name": "SCNi8", "location": "macros.h:2247:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hhi" },
{ "tag": "const", "name": "SCNiLEAST16", "location": "macros.h:2248:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hi" },
{ "tag": "const", "name": "HAVE_INTTYPES_H", "location": "macros.h:2249:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SCNo16", "location": "macros.h:2250:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "ho" },
{ "tag": "const", "name": "HAVE_STRINGS_H", "location": "macros.h:2251:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_STRING_H", "location": "macros.h:2252:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_MEMORY_H", "location": "macros.h:2253:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_MALLOC_H", "location": "macros.h:2254:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_ICONV_H", "location": "macros.h:2255:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_MATH_H", "location": "macros.h:2256:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_CTYPE_H", "location": "macros.h:2257:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_STDINT_H", "location": "macros.h:2258:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SCNuLEAST8", "location": "macros.h:2259:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hhu" },
{ "tag": "const", "name": "HAVE_SYS_TYPES_H", "location": "macros.h:2260:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_LIBC", "location": "macros.h:2261:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_ALLOCA_H", "location": "macros.h:2262:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_PTHREAD_SPINLOCK", "location": "macros.h:2263:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__WORDSIZE_COMPAT32", "location": "macros.h:2264:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_GCC_ATOMICS", "location": "macros.h:2265:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SCNuLEAST16", "location": "macros.h:2266:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hu" },
{ "tag": "const", "name": "__WORDSIZE", "location": "macros.h:2267:18", "type": { "tag": "__int128_t" }, "value": 64 },
{ "tag": "const", "name": "HAVE_STDARG_H", "location": "macros.h:2268:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SCNuFAST8", "location": "macros.h:2269:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hhu" },
{ "tag": "const", "name": "SCNuLEAST64", "location": "macros.h:2270:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lu" },
{ "tag": "const", "name": "HAVE_STDLIB_H", "location": "macros.h:2271:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SCNuFAST16", "location": "macros.h:2272:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lu" },
{ "tag": "const", "name": "STDC_HEADERS", "location": "macros.h:2273:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SCNuFAST32", "location": "macros.h:2274:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lu" },
{ "tag": "const", "name": "SCNuFAST64", "location": "macros.h:2275:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lu" },
{ "tag": "const", "name": "HAVE_STDIO_H", "location": "macros.h:2276:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SCNuLEAST32", "location": "macros.h:2277:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "u" },
{ "tag": "const", "name": "_IONBF", "location": "macros.h:2278:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "SEEK_SET", "location": "macros.h:2279:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "SCNo8", "location": "macros.h:2280:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hho" },
{ "tag": "const", "name": "SEEK_CUR", "location": "macros.h:2281:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SEEK_END", "location": "macros.h:2282:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "P_tmpdir", "location": "macros.h:2283:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "/tmp" },
{ "tag": "const", "name": "TMP_MAX", "location": "macros.h:2284:18", "type": { "tag": "__int128_t" }, "value": 238328 },
{ "tag": "const", "name": "L_tmpnam", "location": "macros.h:2285:18", "type": { "tag": "__int128_t" }, "value": 20 },
{ "tag": "const", "name": "FILENAME_MAX", "location": "macros.h:2286:18", "type": { "tag": "__int128_t" }, "value": 4096 },
{ "tag": "const", "name": "L_ctermid", "location": "macros.h:2287:18", "type": { "tag": "__int128_t" }, "value": 9 },
{ "tag": "const", "name": "FOPEN_MAX", "location": "macros.h:2288:18", "type": { "tag": "__int128_t" }, "value": 16 },
{ "tag": "const", "name": "_ALLOCA_H", "location": "macros.h:2289:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "INTPTR_MIN", "location": "macros.h:2290:18", "type": { "tag": "__int128_t" }, "value": -9223372036854775808 },
{ "tag": "const", "name": "_IOFBF", "location": "macros.h:2291:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "_IOLBF", "location": "macros.h:2292:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_BITS_TYPES_H", "location": "macros.h:2293:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "INT_FAST16_MIN", "location": "macros.h:2294:18", "type": { "tag": "__int128_t" }, "value": -9223372036854775808 },
{ "tag": "const", "name": "INT_FAST32_MIN", "location": "macros.h:2295:18", "type": { "tag": "__int128_t" }, "value": -9223372036854775808 },
{ "tag": "const", "name": "UINT_LEAST64_MAX", "location": "macros.h:2296:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "INT_FAST8_MIN", "location": "macros.h:2297:18", "type": { "tag": "__int128_t" }, "value": -128 },
{ "tag": "const", "name": "UINT_LEAST16_MAX", "location": "macros.h:2298:18", "type": { "tag": "__int128_t" }, "value": 65535 },
{ "tag": "const", "name": "UINT_LEAST32_MAX", "location": "macros.h:2299:18", "type": { "tag": "__int128_t" }, "value": 4294967295 },
{ "tag": "const", "name": "INT_LEAST32_MAX", "location": "macros.h:2300:18", "type": { "tag": "__int128_t" }, "value": 2147483647 },
{ "tag": "const", "name": "UINT_LEAST8_MAX", "location": "macros.h:2301:18", "type": { "tag": "__int128_t" }, "value": 255 },
{ "tag": "const", "name": "INT_LEAST64_MAX", "location": "macros.h:2302:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "UINT_FAST32_MAX", "location": "macros.h:2303:18", "type": { "tag": "__int128_t" }, "value": 18446744073709551615 },
{ "tag": "const", "name": "UINT_FAST64_MAX", "location": "macros.h:2304:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "UINT_FAST8_MAX", "location": "macros.h:2305:18", "type": { "tag": "__int128_t" }, "value": 255 },
{ "tag": "const", "name": "UINT_FAST16_MAX", "location": "macros.h:2306:18", "type": { "tag": "__int128_t" }, "value": 18446744073709551615 },
{ "tag": "const", "name": "INT_FAST16_MAX", "location": "macros.h:2307:18", "type": { "tag": "__int128_t" }, "value": 9223372036854775807 },
{ "tag": "const", "name": "INT_FAST64_MAX", "location": "macros.h:2308:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "INT_FAST32_MAX", "location": "macros.h:2309:18", "type": { "tag": "__int128_t" }, "value": 9223372036854775807 },
{ "tag": "const", "name": "__timespec_defined", "location": "macros.h:2310:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "INT_FAST64_MIN", "location": "macros.h:2311:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "INT_FAST8_MAX", "location": "macros.h:2312:18", "type": { "tag": "__int128_t" }, "value": 127 },
{ "tag": "const", "name": "__timer_t_defined", "location": "macros.h:2313:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "INT64_MAX", "location": "macros.h:2314:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "UINT8_MAX", "location": "macros.h:2315:18", "type": { "tag": "__int128_t" }, "value": 255 },
{ "tag": "const", "name": "INT16_MAX", "location": "macros.h:2316:18", "type": { "tag": "__int128_t" }, "value": 32767 },
{ "tag": "const", "name": "INT32_MAX", "location": "macros.h:2317:18", "type": { "tag": "__int128_t" }, "value": 2147483647 },
{ "tag": "const", "name": "INT32_MIN", "location": "macros.h:2318:18", "type": { "tag": "__int128_t" }, "value": -2147483648 },
{ "tag": "const", "name": "INT64_MIN", "location": "macros.h:2319:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "__clockid_t_defined", "location": "macros.h:2320:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "INT8_MAX", "location": "macros.h:2321:18", "type": { "tag": "__int128_t" }, "value": 127 },
{ "tag": "const", "name": "__clock_t_defined", "location": "macros.h:2322:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "INT8_MIN", "location": "macros.h:2323:18", "type": { "tag": "__int128_t" }, "value": -128 },
{ "tag": "const", "name": "INT16_MIN", "location": "macros.h:2324:18", "type": { "tag": "__int128_t" }, "value": -32768 },
{ "tag": "const", "name": "__time_t_defined", "location": "macros.h:2325:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "INT_LEAST8_MAX", "location": "macros.h:2326:18", "type": { "tag": "__int128_t" }, "value": 127 },
{ "tag": "const", "name": "INT_LEAST16_MAX", "location": "macros.h:2327:18", "type": { "tag": "__int128_t" }, "value": 32767 },
{ "tag": "const", "name": "INT_LEAST32_MIN", "location": "macros.h:2328:18", "type": { "tag": "__int128_t" }, "value": -2147483648 },
{ "tag": "const", "name": "_XLOCALE_H", "location": "macros.h:2329:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "INT_LEAST64_MIN", "location": "macros.h:2330:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "UINT64_MAX", "location": "macros.h:2331:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "INT_LEAST8_MIN", "location": "macros.h:2332:18", "type": { "tag": "__int128_t" }, "value": -128 },
{ "tag": "const", "name": "INT_LEAST16_MIN", "location": "macros.h:2333:18", "type": { "tag": "__int128_t" }, "value": -32768 },
{ "tag": "const", "name": "UINT16_MAX", "location": "macros.h:2334:18", "type": { "tag": "__int128_t" }, "value": 65535 },
{ "tag": "const", "name": "UINT32_MAX", "location": "macros.h:2335:18", "type": { "tag": "__int128_t" }, "value": 4294967295 },
{ "tag": "const", "name": "SDL_PRESSED", "location": "macros.h:2336:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_RELEASED", "location": "macros.h:2337:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "MATH_ERRNO", "location": "macros.h:2338:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "MATH_ERREXCEPT", "location": "macros.h:2339:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "SDL_PATCHLEVEL", "location": "macros.h:2340:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "SDL_MINOR_VERSION", "location": "macros.h:2341:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "SDL_MAJOR_VERSION", "location": "macros.h:2342:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "SDL_INIT_HAPTIC", "location": "macros.h:2343:18", "type": { "tag": "__int128_t" }, "value": 4096 },
{ "tag": "const", "name": "SDL_INIT_JOYSTICK", "location": "macros.h:2344:18", "type": { "tag": "__int128_t" }, "value": 512 },
{ "tag": "const", "name": "SDL_INIT_VIDEO", "location": "macros.h:2345:18", "type": { "tag": "__int128_t" }, "value": 32 },
{ "tag": "const", "name": "SDL_INIT_AUDIO", "location": "macros.h:2346:18", "type": { "tag": "__int128_t" }, "value": 16 },
{ "tag": "const", "name": "SDL_INIT_TIMER", "location": "macros.h:2347:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HUGE", "location": "macros.h:2348:14", "type": { "tag": ":double" }, "value": 3.402823e+38 },
{ "tag": "const", "name": "TLOSS", "location": "macros.h:2349:18", "type": { "tag": "__int128_t" }, "value": 5 },
{ "tag": "const", "name": "PLOSS", "location": "macros.h:2350:18", "type": { "tag": "__int128_t" }, "value": 6 },
{ "tag": "const", "name": "UNDERFLOW", "location": "macros.h:2351:18", "type": { "tag": "__int128_t" }, "value": 4 },
{ "tag": "const", "name": "OVERFLOW", "location": "macros.h:2352:18", "type": { "tag": "__int128_t" }, "value": 3 },
{ "tag": "const", "name": "SING", "location": "macros.h:2353:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "SDL_ICONV_EINVAL", "location": "macros.h:2354:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "X_TLOSS", "location": "macros.h:2355:14", "type": { "tag": ":double" }, "value": 1.414848e+16 },
{ "tag": "const", "name": "DOMAIN", "location": "macros.h:2356:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "M_LN10", "location": "macros.h:2357:14", "type": { "tag": ":double" }, "value": 2.302585e+00 },
{ "tag": "const", "name": "M_LN2", "location": "macros.h:2358:14", "type": { "tag": ":double" }, "value": 6.931472e-01 },
{ "tag": "const", "name": "M_LOG2E", "location": "macros.h:2359:14", "type": { "tag": ":double" }, "value": 1.442695e+00 },
{ "tag": "const", "name": "M_LOG10E", "location": "macros.h:2360:14", "type": { "tag": ":double" }, "value": 4.342945e-01 },
{ "tag": "const", "name": "M_E", "location": "macros.h:2361:14", "type": { "tag": ":double" }, "value": 2.718282e+00 },
{ "tag": "const", "name": "SDLK_SCANCODE_MASK", "location": "macros.h:2362:18", "type": { "tag": "__int128_t" }, "value": 1073741824 },
{ "tag": "const", "name": "SDL_ASSERT_LEVEL", "location": "macros.h:2363:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "SDL_TEXTINPUTEVENT_TEXT_SIZE", "location": "macros.h:2364:18", "type": { "tag": "__int128_t" }, "value": 32 },
{ "tag": "const", "name": "__mbstate_t_defined", "location": "macros.h:2365:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_TEXTEDITINGEVENT_TEXT_SIZE", "location": "macros.h:2366:18", "type": { "tag": "__int128_t" }, "value": 32 },
{ "tag": "const", "name": "_G_config_h", "location": "macros.h:2367:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__FD_ZERO_STOS", "location": "macros.h:2368:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "stosq" },
{ "tag": "const", "name": "_SYS_SELECT_H", "location": "macros.h:2369:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_SIGSET_H_types", "location": "macros.h:2370:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_AUDIO_ALLOW_FORMAT_CHANGE", "location": "macros.h:2371:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "SDL_AUDIO_ALLOW_CHANNELS_CHANGE", "location": "macros.h:2372:18", "type": { "tag": "__int128_t" }, "value": 4 },
{ "tag": "const", "name": "SDL_AUDIO_ALLOW_FREQUENCY_CHANGE", "location": "macros.h:2373:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_SIGSET_NWORDS", "location": "macros.h:2374:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "AUDIO_F32LSB", "location": "macros.h:2375:18", "type": { "tag": "__int128_t" }, "value": 33056 },
{ "tag": "const", "name": "__NFDBITS", "location": "macros.h:2376:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "AUDIO_F32MSB", "location": "macros.h:2377:18", "type": { "tag": "__int128_t" }, "value": 37152 },
{ "tag": "const", "name": "AUDIO_S32LSB", "location": "macros.h:2378:18", "type": { "tag": "__int128_t" }, "value": 32800 },
{ "tag": "const", "name": "_STRUCT_TIMEVAL", "location": "macros.h:2379:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "AUDIO_S32MSB", "location": "macros.h:2380:18", "type": { "tag": "__int128_t" }, "value": 36896 },
{ "tag": "const", "name": "SDL_TOUCH_MOUSEID", "location": "macros.h:2381:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "_MM_HINT_T1", "location": "macros.h:2382:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "_MM_HINT_T2", "location": "macros.h:2383:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_MM_HINT_NTA", "location": "macros.h:2384:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "_MM_HINT_T0", "location": "macros.h:2385:18", "type": { "tag": "__int128_t" }, "value": 3 },
{ "tag": "const", "name": "__MATH_DECLARE_LDOUBLE", "location": "macros.h:2386:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_IO_DEC", "location": "macros.h:2387:18", "type": { "tag": "__int128_t" }, "value": 16 },
{ "tag": "const", "name": "SCNoPTR", "location": "macros.h:2388:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lo" },
{ "tag": "const", "name": "_IO_INTERNAL", "location": "macros.h:2389:18", "type": { "tag": "__int128_t" }, "value": 8 },
{ "tag": "const", "name": "_IO_LEFT", "location": "macros.h:2390:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "_IO_RIGHT", "location": "macros.h:2391:18", "type": { "tag": "__int128_t" }, "value": 4 },
{ "tag": "const", "name": "SCNiPTR", "location": "macros.h:2392:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "li" },
{ "tag": "const", "name": "_IO_SKIPWS", "location": "macros.h:2393:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SCNxMAX", "location": "macros.h:2394:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lx" },
{ "tag": "const", "name": "SCNdPTR", "location": "macros.h:2395:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "ld" },
{ "tag": "const", "name": "SCNuPTR", "location": "macros.h:2396:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lu" },
{ "tag": "const", "name": "_IO_UPPERCASE", "location": "macros.h:2397:18", "type": { "tag": "__int128_t" }, "value": 512 },
{ "tag": "const", "name": "_IO_SHOWPOINT", "location": "macros.h:2398:18", "type": { "tag": "__int128_t" }, "value": 256 },
{ "tag": "const", "name": "_IO_HEX", "location": "macros.h:2399:18", "type": { "tag": "__int128_t" }, "value": 64 },
{ "tag": "const", "name": "_IO_SHOWBASE", "location": "macros.h:2400:18", "type": { "tag": "__int128_t" }, "value": 128 },
{ "tag": "const", "name": "_IO_OCT", "location": "macros.h:2401:18", "type": { "tag": "__int128_t" }, "value": 32 },
{ "tag": "const", "name": "SCNxPTR", "location": "macros.h:2402:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lx" },
{ "tag": "const", "name": "_IO_BAD_SEEN", "location": "macros.h:2403:18", "type": { "tag": "__int128_t" }, "value": 16384 },
{ "tag": "const", "name": "_CTYPE_H", "location": "macros.h:2404:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_IO_IS_FILEBUF", "location": "macros.h:2405:18", "type": { "tag": "__int128_t" }, "value": 8192 },
{ "tag": "const", "name": "_IO_IS_APPENDING", "location": "macros.h:2406:18", "type": { "tag": "__int128_t" }, "value": 4096 },
{ "tag": "const", "name": "_IO_CURRENTLY_PUTTING", "location": "macros.h:2407:18", "type": { "tag": "__int128_t" }, "value": 2048 },
{ "tag": "const", "name": "_IO_FLAGS2_USER_WBUF", "location": "macros.h:2408:18", "type": { "tag": "__int128_t" }, "value": 8 },
{ "tag": "const", "name": "_IO_FLAGS2_NOTCANCEL", "location": "macros.h:2409:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "_IO_FLAGS2_MMAP", "location": "macros.h:2410:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_IO_USER_LOCK", "location": "macros.h:2411:18", "type": { "tag": "__int128_t" }, "value": 32768 },
{ "tag": "const", "name": "SCNx8", "location": "macros.h:2412:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hhx" },
{ "tag": "const", "name": "SCNoFAST64", "location": "macros.h:2413:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lo" },
{ "tag": "const", "name": "SCNoFAST32", "location": "macros.h:2414:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lo" },
{ "tag": "const", "name": "SCNoFAST8", "location": "macros.h:2415:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hho" },
{ "tag": "const", "name": "SCNoFAST16", "location": "macros.h:2416:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lo" },
{ "tag": "const", "name": "_ATFILE_SOURCE", "location": "macros.h:2417:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__USE_POSIX_IMPLICITLY", "location": "macros.h:2418:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SCNxLEAST16", "location": "macros.h:2419:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hx" },
{ "tag": "const", "name": "SCNxLEAST8", "location": "macros.h:2420:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hhx" },
{ "tag": "const", "name": "SCNx64", "location": "macros.h:2421:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lx" },
{ "tag": "const", "name": "SCNx16", "location": "macros.h:2422:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hx" },
{ "tag": "const", "name": "SCNx32", "location": "macros.h:2423:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "x" },
{ "tag": "const", "name": "__GLIBC_MINOR__", "location": "macros.h:2424:18", "type": { "tag": "__int128_t" }, "value": 15 },
{ "tag": "const", "name": "SCNxFAST32", "location": "macros.h:2425:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lx" },
{ "tag": "const", "name": "SCNxFAST8", "location": "macros.h:2426:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hhx" },
{ "tag": "const", "name": "SCNxFAST16", "location": "macros.h:2427:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lx" },
{ "tag": "const", "name": "__GNU_LIBRARY__", "location": "macros.h:2428:18", "type": { "tag": "__int128_t" }, "value": 6 },
{ "tag": "const", "name": "SCNxLEAST64", "location": "macros.h:2429:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lx" },
{ "tag": "const", "name": "_IO_SHOWPOS", "location": "macros.h:2430:18", "type": { "tag": "__int128_t" }, "value": 1024 },
{ "tag": "const", "name": "SCNxLEAST32", "location": "macros.h:2431:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "x" },
{ "tag": "const", "name": "__GLIBC__", "location": "macros.h:2432:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "__STDC_IEC_559_COMPLEX__", "location": "macros.h:2433:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SCNuMAX", "location": "macros.h:2434:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lu" },
{ "tag": "const", "name": "__STDC_ISO_10646__", "location": "macros.h:2435:18", "type": { "tag": "__int128_t" }, "value": 200009 },
{ "tag": "const", "name": "SCNiMAX", "location": "macros.h:2436:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "li" },
{ "tag": "const", "name": "SCNoMAX", "location": "macros.h:2437:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lo" },
{ "tag": "const", "name": "SCNdMAX", "location": "macros.h:2438:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "ld" },
{ "tag": "const", "name": "__STDC_IEC_559__", "location": "macros.h:2439:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SCNxFAST64", "location": "macros.h:2440:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lx" },
{ "tag": "const", "name": "_IO_UNIFIED_JUMPTABLES", "location": "macros.h:2441:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_SYS_CDEFS_H", "location": "macros.h:2442:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__GNUC_VA_LIST", "location": "macros.h:2443:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__GLIBC_HAVE_LONG_LONG", "location": "macros.h:2444:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_IOS_ATEND", "location": "macros.h:2445:18", "type": { "tag": "__int128_t" }, "value": 4 },
{ "tag": "const", "name": "_IOS_APPEND", "location": "macros.h:2446:18", "type": { "tag": "__int128_t" }, "value": 8 },
{ "tag": "const", "name": "EOF", "location": "macros.h:2447:18", "type": { "tag": "__int128_t" }, "value": -1 },
{ "tag": "const", "name": "_IOS_INPUT", "location": "macros.h:2448:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_IOS_OUTPUT", "location": "macros.h:2449:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "SCNo32", "location": "macros.h:2450:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "o" },
{ "tag": "const", "name": "SCNo64", "location": "macros.h:2451:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lo" },
{ "tag": "const", "name": "SCNoLEAST64", "location": "macros.h:2452:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lo" },
{ "tag": "const", "name": "SCNoLEAST8", "location": "macros.h:2453:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "hho" },
{ "tag": "const", "name": "SCNoLEAST16", "location": "macros.h:2454:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "ho" },
{ "tag": "const", "name": "SCNoLEAST32", "location": "macros.h:2455:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "o" },
{ "tag": "const", "name": "_IO_EOF_SEEN", "location": "macros.h:2456:18", "type": { "tag": "__int128_t" }, "value": 16 },
{ "tag": "const", "name": "_IO_ERR_SEEN", "location": "macros.h:2457:18", "type": { "tag": "__int128_t" }, "value": 32 },
{ "tag": "const", "name": "_IO_NO_READS", "location": "macros.h:2458:18", "type": { "tag": "__int128_t" }, "value": 4 },
{ "tag": "const", "name": "_IO_NO_WRITES", "location": "macros.h:2459:18", "type": { "tag": "__int128_t" }, "value": 8 },
{ "tag": "const", "name": "_IO_LINE_BUF", "location": "macros.h:2460:18", "type": { "tag": "__int128_t" }, "value": 512 },
{ "tag": "const", "name": "_IO_TIED_PUT_GET", "location": "macros.h:2461:18", "type": { "tag": "__int128_t" }, "value": 1024 },
{ "tag": "const", "name": "_IO_IN_BACKUP", "location": "macros.h:2462:18", "type": { "tag": "__int128_t" }, "value": 256 },
{ "tag": "const", "name": "_IO_DELETE_DONT_CLOSE", "location": "macros.h:2463:18", "type": { "tag": "__int128_t" }, "value": 64 },
{ "tag": "const", "name": "_IO_LINKED", "location": "macros.h:2464:18", "type": { "tag": "__int128_t" }, "value": 128 },
{ "tag": "const", "name": "_IOS_NOREPLACE", "location": "macros.h:2465:18", "type": { "tag": "__int128_t" }, "value": 64 },
{ "tag": "const", "name": "_IOS_BIN", "location": "macros.h:2466:18", "type": { "tag": "__int128_t" }, "value": 128 },
{ "tag": "const", "name": "_IOS_TRUNC", "location": "macros.h:2467:18", "type": { "tag": "__int128_t" }, "value": 16 },
{ "tag": "const", "name": "_IOS_NOCREATE", "location": "macros.h:2468:18", "type": { "tag": "__int128_t" }, "value": 32 },
{ "tag": "const", "name": "_IO_USER_BUF", "location": "macros.h:2469:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_IO_UNBUFFERED", "location": "macros.h:2470:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "_IO_MAGIC", "location": "macros.h:2471:18", "type": { "tag": "__int128_t" }, "value": 4222418944 },
{ "tag": "const", "name": "_OLD_STDIO_MAGIC", "location": "macros.h:2472:18", "type": { "tag": "__int128_t" }, "value": 4206624768 },
{ "tag": "const", "name": "_IO_MAGIC_MASK", "location": "macros.h:2473:18", "type": { "tag": "__int128_t" }, "value": 4294901760 },
{ "tag": "const", "name": "HAVE_MALLOC", "location": "macros.h:2474:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_HAPTIC_CONSTANT", "location": "macros.h:2475:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_HAPTIC_SQUARE", "location": "macros.h:2476:18", "type": { "tag": "__int128_t" }, "value": 4 },
{ "tag": "const", "name": "SDL_HAPTIC_SINE", "location": "macros.h:2477:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "SDL_IGNORE", "location": "macros.h:2478:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "SDL_QUERY", "location": "macros.h:2479:18", "type": { "tag": "__int128_t" }, "value": -1 },
{ "tag": "const", "name": "SDL_ENABLE", "location": "macros.h:2480:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_DISABLE", "location": "macros.h:2481:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "_MATH_H", "location": "macros.h:2482:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_HAPTIC_CUSTOM", "location": "macros.h:2483:18", "type": { "tag": "__int128_t" }, "value": 2048 },
{ "tag": "const", "name": "SDL_HAPTIC_FRICTION", "location": "macros.h:2484:18", "type": { "tag": "__int128_t" }, "value": 1024 },
{ "tag": "const", "name": "FP_ILOGB0", "location": "macros.h:2485:18", "type": { "tag": "__int128_t" }, "value": -2147483648 },
{ "tag": "const", "name": "SDL_HAPTIC_INERTIA", "location": "macros.h:2486:18", "type": { "tag": "__int128_t" }, "value": 512 },
{ "tag": "const", "name": "FP_ILOGBNAN", "location": "macros.h:2487:18", "type": { "tag": "__int128_t" }, "value": -2147483648 },
{ "tag": "const", "name": "SDL_HAPTIC_DAMPER", "location": "macros.h:2488:18", "type": { "tag": "__int128_t" }, "value": 256 },
{ "tag": "const", "name": "SDL_HAPTIC_PAUSE", "location": "macros.h:2489:18", "type": { "tag": "__int128_t" }, "value": 32768 },
{ "tag": "const", "name": "SDL_HAPTIC_STATUS", "location": "macros.h:2490:18", "type": { "tag": "__int128_t" }, "value": 16384 },
{ "tag": "const", "name": "SDL_HAPTIC_AUTOCENTER", "location": "macros.h:2491:18", "type": { "tag": "__int128_t" }, "value": 8192 },
{ "tag": "const", "name": "SDL_HAPTIC_GAIN", "location": "macros.h:2492:18", "type": { "tag": "__int128_t" }, "value": 4096 },
{ "tag": "const", "name": "SDL_HAPTIC_INFINITY", "location": "macros.h:2493:18", "type": { "tag": "__int128_t" }, "value": 4294967295 },
{ "tag": "const", "name": "NAN", "location": "macros.h:2494:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } } },
{ "tag": "const", "name": "SDL_HAPTIC_SPHERICAL", "location": "macros.h:2495:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "SDL_HAPTIC_CARTESIAN", "location": "macros.h:2496:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_HAPTIC_POLAR", "location": "macros.h:2497:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "_MATH_H_MATHDEF", "location": "macros.h:2498:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "M_SQRT1_2", "location": "macros.h:2499:14", "type": { "tag": ":double" }, "value": 7.071068e-01 },
{ "tag": "const", "name": "SDL_HAPTIC_TRIANGLE", "location": "macros.h:2500:18", "type": { "tag": "__int128_t" }, "value": 8 },
{ "tag": "const", "name": "M_2_SQRTPI", "location": "macros.h:2501:14", "type": { "tag": ":double" }, "value": 1.128379e+00 },
{ "tag": "const", "name": "M_SQRT2", "location": "macros.h:2502:14", "type": { "tag": ":double" }, "value": 1.414214e+00 },
{ "tag": "const", "name": "M_2_PI", "location": "macros.h:2503:14", "type": { "tag": ":double" }, "value": 6.366198e-01 },
{ "tag": "const", "name": "M_1_PI", "location": "macros.h:2504:14", "type": { "tag": ":double" }, "value": 3.183099e-01 },
{ "tag": "const", "name": "M_PI_4", "location": "macros.h:2505:14", "type": { "tag": ":double" }, "value": 7.853982e-01 },
{ "tag": "const", "name": "SDL_HAPTIC_RAMP", "location": "macros.h:2506:18", "type": { "tag": "__int128_t" }, "value": 64 },
{ "tag": "const", "name": "SDL_HAPTIC_SPRING", "location": "macros.h:2507:18", "type": { "tag": "__int128_t" }, "value": 128 },
{ "tag": "const", "name": "M_PI_2", "location": "macros.h:2508:14", "type": { "tag": ":double" }, "value": 1.570796e+00 },
{ "tag": "const", "name": "M_PI", "location": "macros.h:2509:14", "type": { "tag": ":double" }, "value": 3.141593e+00 },
{ "tag": "const", "name": "SDL_HAPTIC_SAWTOOTHDOWN", "location": "macros.h:2510:18", "type": { "tag": "__int128_t" }, "value": 32 },
{ "tag": "const", "name": "SDL_HAPTIC_SAWTOOTHUP", "location": "macros.h:2511:18", "type": { "tag": "__int128_t" }, "value": 16 },
{ "tag": "const", "name": "UINTPTR_MAX", "location": "macros.h:2512:18", "type": { "tag": "__int128_t" }, "value": 18446744073709551615 },
{ "tag": "const", "name": "INTMAX_MIN", "location": "macros.h:2513:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "INTMAX_MAX", "location": "macros.h:2514:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "UINTMAX_MAX", "location": "macros.h:2515:18", "type": { "tag": "__int128_t" } },
{ "tag": "const", "name": "PTRDIFF_MIN", "location": "macros.h:2516:18", "type": { "tag": "__int128_t" }, "value": -9223372036854775808 },
{ "tag": "const", "name": "SIG_ATOMIC_MIN", "location": "macros.h:2517:18", "type": { "tag": "__int128_t" }, "value": -2147483648 },
{ "tag": "const", "name": "PTRDIFF_MAX", "location": "macros.h:2518:18", "type": { "tag": "__int128_t" }, "value": 9223372036854775807 },
{ "tag": "const", "name": "SIG_ATOMIC_MAX", "location": "macros.h:2519:18", "type": { "tag": "__int128_t" }, "value": 2147483647 },
{ "tag": "const", "name": "SIZE_MAX", "location": "macros.h:2520:18", "type": { "tag": "__int128_t" }, "value": 18446744073709551615 },
{ "tag": "const", "name": "INTPTR_MAX", "location": "macros.h:2521:18", "type": { "tag": "__int128_t" }, "value": 9223372036854775807 },
{ "tag": "const", "name": "__ldiv_t_defined", "location": "macros.h:2522:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__lldiv_t_defined", "location": "macros.h:2523:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIdFAST16", "location": "macros.h:2524:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "ld" },
{ "tag": "const", "name": "PRIdFAST8", "location": "macros.h:2525:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "d" },
{ "tag": "const", "name": "PRIdLEAST64", "location": "macros.h:2526:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "ld" },
{ "tag": "const", "name": "PRIdFAST64", "location": "macros.h:2527:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "ld" },
{ "tag": "const", "name": "PRIdFAST32", "location": "macros.h:2528:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "ld" },
{ "tag": "const", "name": "PRIi32", "location": "macros.h:2529:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "i" },
{ "tag": "const", "name": "PRIi16", "location": "macros.h:2530:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "i" },
{ "tag": "const", "name": "PRIi8", "location": "macros.h:2531:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "i" },
{ "tag": "const", "name": "PRIiLEAST8", "location": "macros.h:2532:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "i" },
{ "tag": "const", "name": "PRIi64", "location": "macros.h:2533:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "li" },
{ "tag": "const", "name": "__PRIPTR_PREFIX", "location": "macros.h:2534:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "l" },
{ "tag": "const", "name": "__PRI64_PREFIX", "location": "macros.h:2535:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "l" },
{ "tag": "const", "name": "PRId32", "location": "macros.h:2536:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "d" },
{ "tag": "const", "name": "PRId16", "location": "macros.h:2537:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "d" },
{ "tag": "const", "name": "PRId8", "location": "macros.h:2538:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "d" },
{ "tag": "const", "name": "PRIdLEAST8", "location": "macros.h:2539:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "d" },
{ "tag": "const", "name": "PRId64", "location": "macros.h:2540:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "ld" },
{ "tag": "const", "name": "PRIdLEAST32", "location": "macros.h:2541:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "d" },
{ "tag": "const", "name": "PRIdLEAST16", "location": "macros.h:2542:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "d" },
{ "tag": "const", "name": "____gwchar_t_defined", "location": "macros.h:2543:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "WINT_MAX", "location": "macros.h:2544:18", "type": { "tag": "__int128_t" }, "value": 4294967295 },
{ "tag": "const", "name": "WINT_MIN", "location": "macros.h:2545:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "HAVE_SINF", "location": "macros.h:2546:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_SIN", "location": "macros.h:2547:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_FSEEKO", "location": "macros.h:2548:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_SQRT", "location": "macros.h:2549:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_SIGACTION", "location": "macros.h:2550:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_FSEEKO64", "location": "macros.h:2551:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_SETJMP", "location": "macros.h:2552:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_NANOSLEEP", "location": "macros.h:2553:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_SA_SIGACTION", "location": "macros.h:2554:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIu64", "location": "macros.h:2555:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lu" },
{ "tag": "const", "name": "HAVE_COPYSIGN", "location": "macros.h:2556:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_ATAN2", "location": "macros.h:2557:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIuLEAST8", "location": "macros.h:2558:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "u" },
{ "tag": "const", "name": "HAVE_CEIL", "location": "macros.h:2559:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_COSF", "location": "macros.h:2560:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIu8", "location": "macros.h:2561:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "u" },
{ "tag": "const", "name": "PRIu32", "location": "macros.h:2562:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "u" },
{ "tag": "const", "name": "HAVE_COS", "location": "macros.h:2563:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIu16", "location": "macros.h:2564:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "u" },
{ "tag": "const", "name": "HAVE_FLOOR", "location": "macros.h:2565:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIuLEAST64", "location": "macros.h:2566:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lu" },
{ "tag": "const", "name": "HAVE_FABS", "location": "macros.h:2567:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_POW", "location": "macros.h:2568:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_SCALBN", "location": "macros.h:2569:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_LOG", "location": "macros.h:2570:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIuLEAST16", "location": "macros.h:2571:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "u" },
{ "tag": "const", "name": "PRIuLEAST32", "location": "macros.h:2572:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "u" },
{ "tag": "const", "name": "PRIoLEAST16", "location": "macros.h:2573:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "o" },
{ "tag": "const", "name": "SDL_AUDIO_DRIVER_DUMMY", "location": "macros.h:2574:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIoLEAST32", "location": "macros.h:2575:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "o" },
{ "tag": "const", "name": "SDL_AUDIO_DRIVER_DISK", "location": "macros.h:2576:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_INPUT_LINUXEV", "location": "macros.h:2577:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIo64", "location": "macros.h:2578:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lo" },
{ "tag": "const", "name": "SDL_AUDIO_DRIVER_OSS", "location": "macros.h:2579:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIoLEAST8", "location": "macros.h:2580:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "o" },
{ "tag": "const", "name": "SDL_HAPTIC_LINUX", "location": "macros.h:2581:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIoFAST32", "location": "macros.h:2582:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lo" },
{ "tag": "const", "name": "SDL_JOYSTICK_LINUX", "location": "macros.h:2583:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIoFAST64", "location": "macros.h:2584:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lo" },
{ "tag": "const", "name": "PRIoLEAST64", "location": "macros.h:2585:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lo" },
{ "tag": "const", "name": "SDL_LOADSO_DLOPEN", "location": "macros.h:2586:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIoFAST16", "location": "macros.h:2587:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "lo" },
{ "tag": "const", "name": "PRIiLEAST64", "location": "macros.h:2588:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "li" },
{ "tag": "const", "name": "HAVE_CLOCK_GETTIME", "location": "macros.h:2589:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIoFAST8", "location": "macros.h:2590:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "o" },
{ "tag": "const", "name": "PRIiFAST8", "location": "macros.h:2591:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "i" },
{ "tag": "const", "name": "HAVE_SYSCONF", "location": "macros.h:2592:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIiFAST16", "location": "macros.h:2593:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "li" },
{ "tag": "const", "name": "HAVE_ICONV", "location": "macros.h:2594:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIiLEAST16", "location": "macros.h:2595:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "i" },
{ "tag": "const", "name": "HAVE_MPROTECT", "location": "macros.h:2596:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIiLEAST32", "location": "macros.h:2597:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "i" },
{ "tag": "const", "name": "HAVE_SEM_TIMEDWAIT", "location": "macros.h:2598:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIo8", "location": "macros.h:2599:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "o" },
{ "tag": "const", "name": "HAVE_PTHREAD_SETNAME_NP", "location": "macros.h:2600:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIo16", "location": "macros.h:2601:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "o" },
{ "tag": "const", "name": "SDL_AUDIO_DRIVER_ALSA_DYNAMIC", "location": "macros.h:2602:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "libasound.so.2" },
{ "tag": "const", "name": "SDL_CACHELINE_SIZE", "location": "macros.h:2603:18", "type": { "tag": "__int128_t" }, "value": 128 },
{ "tag": "const", "name": "PRIo32", "location": "macros.h:2604:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "o" },
{ "tag": "const", "name": "PRIiFAST32", "location": "macros.h:2605:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "li" },
{ "tag": "const", "name": "SDL_AUDIO_DRIVER_ALSA", "location": "macros.h:2606:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "PRIiFAST64", "location": "macros.h:2607:13", "type": { "tag": ":pointer", "type": { "tag": ":char" } }, "value": "li" },
{ "tag": "const", "name": "HAVE_ABS", "location": "macros.h:2608:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_BCOPY", "location": "macros.h:2609:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_MEMSET", "location": "macros.h:2610:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_MEMCPY", "location": "macros.h:2611:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_MEMMOVE", "location": "macros.h:2612:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_MEMCMP", "location": "macros.h:2613:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_STRLEN", "location": "macros.h:2614:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_STRDUP", "location": "macros.h:2615:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_STRCHR", "location": "macros.h:2616:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_CALLOC", "location": "macros.h:2617:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__SIZEOF_PTHREAD_ATTR_T", "location": "macros.h:2618:18", "type": { "tag": "__int128_t" }, "value": 56 },
{ "tag": "const", "name": "HAVE_REALLOC", "location": "macros.h:2619:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_BITS_PTHREADTYPES_H", "location": "macros.h:2620:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_FREE", "location": "macros.h:2621:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_ALLOCA", "location": "macros.h:2622:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_GETENV", "location": "macros.h:2623:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_ALPHA_TRANSPARENT", "location": "macros.h:2624:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "__SIZEOF_PTHREAD_COND_T", "location": "macros.h:2625:18", "type": { "tag": "__int128_t" }, "value": 48 },
{ "tag": "const", "name": "HAVE_SETENV", "location": "macros.h:2626:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_ALPHA_OPAQUE", "location": "macros.h:2627:18", "type": { "tag": "__int128_t" }, "value": 255 },
{ "tag": "const", "name": "__SIZEOF_PTHREAD_MUTEXATTR_T", "location": "macros.h:2628:18", "type": { "tag": "__int128_t" }, "value": 4 },
{ "tag": "const", "name": "HAVE_PUTENV", "location": "macros.h:2629:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__SIZEOF_PTHREAD_MUTEX_T", "location": "macros.h:2630:18", "type": { "tag": "__int128_t" }, "value": 40 },
{ "tag": "const", "name": "HAVE_UNSETENV", "location": "macros.h:2631:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_QSORT", "location": "macros.h:2632:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_STRNCMP", "location": "macros.h:2633:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__SIZEOF_PTHREAD_BARRIER_T", "location": "macros.h:2634:18", "type": { "tag": "__int128_t" }, "value": 32 },
{ "tag": "const", "name": "HAVE_STRCMP", "location": "macros.h:2635:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_STRCASECMP", "location": "macros.h:2636:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__SIZEOF_PTHREAD_RWLOCKATTR_T", "location": "macros.h:2637:18", "type": { "tag": "__int128_t" }, "value": 8 },
{ "tag": "const", "name": "HAVE_STRNCASECMP", "location": "macros.h:2638:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__SIZEOF_PTHREAD_RWLOCK_T", "location": "macros.h:2639:18", "type": { "tag": "__int128_t" }, "value": 56 },
{ "tag": "const", "name": "HAVE_SSCANF", "location": "macros.h:2640:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__SIZEOF_PTHREAD_CONDATTR_T", "location": "macros.h:2641:18", "type": { "tag": "__int128_t" }, "value": 4 },
{ "tag": "const", "name": "HAVE_SNPRINTF", "location": "macros.h:2642:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_VSNPRINTF", "location": "macros.h:2643:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__SIZEOF_PTHREAD_BARRIERATTR_T", "location": "macros.h:2644:18", "type": { "tag": "__int128_t" }, "value": 4 },
{ "tag": "const", "name": "HAVE_ATAN", "location": "macros.h:2645:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_STRRCHR", "location": "macros.h:2646:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_STRTOL", "location": "macros.h:2647:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_STRSTR", "location": "macros.h:2648:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_STRTOUL", "location": "macros.h:2649:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_STRTOLL", "location": "macros.h:2650:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_STRTOULL", "location": "macros.h:2651:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_STRTOD", "location": "macros.h:2652:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_ATOI", "location": "macros.h:2653:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "HAVE_ATOF", "location": "macros.h:2654:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__PTHREAD_MUTEX_HAVE_PREV", "location": "macros.h:2655:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_STDIO_H", "location": "macros.h:2656:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__FILE_defined", "location": "macros.h:2657:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "____FILE_defined", "location": "macros.h:2658:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_HAT_UP", "location": "macros.h:2659:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "SDL_HAT_CENTERED", "location": "macros.h:2660:18", "type": { "tag": "__int128_t" }, "value": 0 },
{ "tag": "const", "name": "SDL_HAT_RIGHT", "location": "macros.h:2661:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "SDL_HAT_DOWN", "location": "macros.h:2662:18", "type": { "tag": "__int128_t" }, "value": 4 },
{ "tag": "const", "name": "SDL_HAT_LEFT", "location": "macros.h:2663:18", "type": { "tag": "__int128_t" }, "value": 8 },
{ "tag": "const", "name": "_SYS_SYSMACROS_H", "location": "macros.h:2664:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "_STDLIB_H", "location": "macros.h:2665:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "WEXITED", "location": "macros.h:2666:18", "type": { "tag": "__int128_t" }, "value": 4 },
{ "tag": "const", "name": "WSTOPPED", "location": "macros.h:2667:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "WUNTRACED", "location": "macros.h:2668:18", "type": { "tag": "__int128_t" }, "value": 2 },
{ "tag": "const", "name": "WNOHANG", "location": "macros.h:2669:18", "type": { "tag": "__int128_t" }, "value": 1 },
{ "tag": "const", "name": "__WCLONE", "location": "macros.h:2670:18", "type": { "tag": "__int128_t" }, "value": 2147483648 },
{ "tag": "const", "name": "__WALL", "location": "macros.h:2671:18", "type": { "tag": "__int128_t" }, "value": 1073741824 },
{ "tag": "const", "name": "__WNOTHREAD", "location": "macros.h:2672:18", "type": { "tag": "__int128_t" }, "value": 536870912 },
{ "tag": "const", "name": "WNOWAIT", "location": "macros.h:2673:18", "type": { "tag": "__int128_t" }, "value": 16777216 },
{ "tag": "const", "name": "WCONTINUED", "location": "macros.h:2674:18", "type": { "tag": "__int128_t" }, "value": 8 },
{ "tag": "const", "name": "__W_CONTINUED", "location": "macros.h:2675:18", "type": { "tag": "__int128_t" }, "value": 65535 },
{ "tag": "const", "name": "__WCOREFLAG", "location": "macros.h:2676:18", "type": { "tag": "__int128_t" }, "value": 128 }
]
