(in-package #:sdl2)

(defun joystick-update ()
  (sdl-joystick-update))

(defun joystick-count ()
  (check-rc (sdl-num-joysticks)))

(defun joystick-opened (device-index)
  ;; TODO this is documented in the wiki but doesn't seem to be
  ;; generated by c2ffi. Perhaps it's not released yet?
  (check-rc (sdl-joystick-opened device-index)))

(defun joystick-open (device-index)
  (sdl-collect
   (check-null (sdl2-ffi::sdl-joystick-open device-index))
   (lambda (j) (sdl-joystick-close j))))

(defun joystick-close (joystick)
  (sdl-joystick-close joystick)
  (sdl-cancel-collect joystick))

(defun joystick-name-for-index (device-index)
  (check-null (sdl-joystick-name-for-index device-index)))

(defun joystick-name (joystick)
  (check-null (sdl-joystick-name joystick)))

(defmacro joystick-caps-query (fn joystick)
  `(check-rc (,fn ,joystick)))

(defun joystick-hat-count (joystick)
  (joystick-caps-query sdl-joystick-num-hats joystick))

(defun joystick-axis-count (joystick)
  (joystick-caps-query sdl-joystick-num-axes joystick))

(defun joystick-ball-count (joystick)
  (joystick-caps-query sdl-joystick-num-balls joystick))

(defun joystick-button-count (joystick)
  (joystick-caps-query sdl-joystick-num-buttons joystick))




