(in-package #:sdl2)


(defwrapper sdl-joystick ())

(defun joystick-update ()
  (sdl2-ffi::sdl-joystickupdate))

(defun joystick-count ()
  (check-rc (sdl2-ffi::sdl-numjoysticks)))

(defun joystick-opened (device-index)
  ;; TODO this is documented in the wiki but doesn't seem to be
  ;; generated by c2ffi. Perhaps it's not released yet?
  (check-rc (sdl2-ffi::sdl-joystickopened device-index)))

(defun joystick-open (device-index)
  (sdl-collect
   (%make-sdl-joystick :ptr (check-null (sdl2-ffi::sdl-joystickopen device-index)))
   #'sdl2-ffi::sdl-joystickclose))

(defun joystick-close (joystick)
  (sdl2-ffi::sdl-joystickclose (sdl-ptr joystick))
  (sdl-cancel-collect joystick))

(defun joystick-name-for-index (device-index)
  (check-null (sdl2-ffi::sdl-joysticknameforindex device-index)))

(defun joystick-name (joystick)
  (check-null (sdl2-ffi::sdl-joystickname (sdl-ptr joystick))))

(defmacro joystick-caps-query (fn joystick)
  `(check-rc (,fn (sdl-ptr ,joystick))))

(defun joystick-hat-count (joystick)
  (joystick-caps-query sdl2-ffi::sdl-joysticknumhats joystick))

(defun joystick-axis-count (joystick)
  (joystick-caps-query sdl2-ffi::sdl-joysticknumaxes joystick))

(defun joystick-ball-count (joystick)
  (joystick-caps-query sdl2-ffi::sdl-joysticknumballs joystick))

(defun joystick-button-count (joystick)
  (joystick-caps-query sdl2-ffi::sdl-joysticknumbuttons joystick))




